In [6]:
using HDF5

In [7]:
TRAIN_DATA_PATH="datasets/train_catvnoncat.h5"
TEST_DATA_PATH="datasets/test_catvnoncat.h5"

"datasets/test_catvnoncat.h5"

In [8]:
train_data_x_orig = h5read(TRAIN_DATA_PATH, "train_set_x")
train_data_y_orig = h5read(TRAIN_DATA_PATH, "train_set_y")

209-element Array{Int64,1}:
 0
 0
 1
 0
 0
 0
 0
 1
 0
 0
 0
 1
 0
 ⋮
 1
 0
 0
 1
 0
 0
 0
 0
 0
 0
 0
 0

In [9]:
test_data_x_orig = h5read(TEST_DATA_PATH, "test_set_x")
test_data_y_orig = h5read(TEST_DATA_PATH, "test_set_y")

50-element Array{Int64,1}:
 1
 1
 1
 1
 1
 0
 1
 1
 1
 1
 1
 1
 1
 ⋮
 0
 0
 1
 1
 1
 0
 0
 0
 1
 1
 1
 0

In [10]:
classes = h5read(TEST_DATA_PATH, "list_classes")

2-element Array{String,1}:
 "non-cat"
 "cat"    

In [11]:
train_data_y_orig = reshape(train_data_y_orig, (1, size(train_data_y_orig)[1]))

1×209 Array{Int64,2}:
 0  0  1  0  0  0  0  1  0  0  0  1  0  …  1  0  0  1  0  0  0  0  0  0  0  0

In [12]:
test_data_y_orig = reshape(test_data_y_orig, (1, size(test_data_y_orig)[1]))

1×50 Array{Int64,2}:
 1  1  1  1  1  0  1  1  1  1  1  1  1  …  0  0  1  1  1  0  0  0  1  1  1  0

In [13]:
function reshape_image_array(image_array::Array{UInt8,4})
    return reshape(image_array, :, size(image_array)[4])
end
function reshape_image_array_reverse(image_array::Array{UInt8,2})
    return reshape(image_array, 64, 64, 3, :)
end

reshape_image_array_reverse (generic function with 1 method)

In [14]:
test_data_x = reshape_image_array(test_data_x_orig) ./ 255
test_data_x = Array{Float32, 2}(test_data_x)

12288×50 Array{Float32,2}:
 0.619608  0.45098   1.0       0.996078  …  0.160784  0.0705882  0.521569 
 0.407843  0.431373  0.992157  0.996078     0.184314  0.0705882  0.639216 
 0.32549   0.435294  0.996078  0.952941     0.329412  0.0627451  0.294118 
 0.631373  0.537255  1.0       1.0          0.282353  0.137255   0.384314 
 0.415686  0.505882  0.992157  1.0          0.305882  0.141176   0.470588 
 0.333333  0.505882  0.996078  0.964706  …  0.439216  0.121569   0.172549 
 0.635294  0.607843  1.0       1.0          0.403922  0.211765   0.423529 
 0.419608  0.572549  0.992157  1.0          0.4       0.223529   0.517647 
 0.329412  0.568627  0.996078  0.992157     0.486275  0.203922   0.184314 
 0.639216  0.623529  1.0       1.0          0.466667  0.313726   0.462745 
 0.419608  0.596078  0.992157  1.0       …  0.447059  0.345098   0.576471 
 0.329412  0.572549  0.996078  1.0          0.505882  0.313726   0.223529 
 0.639216  0.607843  1.0       1.0          0.529412  0.407843   0.403922

In [15]:
train_data_x = reshape_image_array(train_data_x_orig) ./ 255
train_data_x = Array{Float32, 2}(train_data_x)

12288×209 Array{Float32,2}:
 0.0666667  0.768627  0.321569  0.00392157  …  0.560784  0.0862745  0.0313726
 0.121569   0.752941  0.278431  0.0862745      0.607843  0.0941176  0.109804 
 0.219608   0.745098  0.266667  0.00784314     0.647059  0.0901961  0.207843 
 0.0862745  0.756863  0.34902   0.00392157     0.721569  0.0901961  0.054902 
 0.129412   0.729412  0.32549   0.054902       0.745098  0.0980392  0.129412 
 0.231373   0.713726  0.32549   0.00784314  …  0.776471  0.0941176  0.227451 
 0.0980392  0.737255  0.392157  0.00392157     0.556863  0.0941176  0.0745098
 0.137255   0.701961  0.384314  0.0509804      0.584314  0.101961   0.137255 
 0.243137   0.682353  0.407843  0.00392157     0.607843  0.0980392  0.239216 
 0.0980392  0.835294  0.415686  0.0156863      0.529412  0.0941176  0.0745098
 0.137255   0.760784  0.411765  0.113725    …  0.580392  0.101961   0.137255 
 0.243137   0.756863  0.454902  0.0117647      0.596078  0.105882   0.239216 
 0.105882   0.658824  0.462745  0.03

In [16]:
using Statistics, BenchmarkTools

In [60]:
include("../../NeuralNetwork.jl")

predict

In [61]:
layer_dims = [12288, 7, 1]

3-element Array{Int64,1}:
 12288
     7
     1

In [62]:
parameters2, activations2 = neural_network_dense(train_data_x, train_data_y_orig, layer_dims, 100, 0.0075)

Cost at iteration 100 is 0.6706643


(Dict{String,Array{Float32,N} where N}("W2" => [0.065906264 0.008531705 … 0.40763798 0.58506685],"W1" => [0.009794031 0.0051650545 … 0.0069414983 0.0021731728; 0.004426979 -0.0059097195 … 0.0047761872 -0.0039415965; … ; -0.007328883 0.01659493 … -0.005471624 0.016419603; 0.022440376 -0.015417081 … 0.0098485965 0.0037002328],"b2" => [-0.10878273],"b1" => [-0.0003705971; -3.0539883e-5; … ; -0.0007448625; -0.00048012656]), (relu, sigmoid))

In [66]:
print_timer(to)

 ──────────────────────────────────────────────────────────────────────────────
                                       Time                   Allocations      
                               ──────────────────────   ───────────────────────
       Tot / % measured:             847s / 2.24%           14.0GiB / 98.6%    

 Section               ncalls     time   %tot     avg     alloc   %tot      avg
 ──────────────────────────────────────────────────────────────────────────────
 Actual training            2    19.0s   100%   9.49s   13.8GiB  100%   6.91GiB
   backprop             1.10k    13.5s  70.9%  12.2ms   12.0GiB  86.8%  11.2MiB
     calculate dA       2.20k    6.79s  35.7%  3.09ms   10.5GiB  76.2%  4.90MiB
     calculate dw       2.20k    6.10s  32.1%  2.77ms   1.41GiB  10.2%   673KiB
     calculate dZ       2.20k    177ms  0.93%  80.4μs   25.0MiB  0.18%  11.7KiB
     calculate db       2.20k   78.2ms  0.41%  35.6μs   1.83MiB  0.01%     872B
     Initial dA         1.10k   8.92ms 

In [64]:
parameters, activations = neural_network_dense(train_data_x, train_data_y_orig, layer_dims, 1000, 0.0075)

Cost at iteration 100 is 0.5489433
Cost at iteration 200 is 0.48521948
Cost at iteration 300 is 0.4378766
Cost at iteration 400 is 0.39246276
Cost at iteration 500 is 0.33319694
Cost at iteration 600 is 0.26842335
Cost at iteration 700 is 0.21762599
Cost at iteration 800 is 0.18310715
Cost at iteration 900 is 0.16040407
Cost at iteration 1000 is 0.14216802


(Dict{String,Array{Float32,N} where N}("W2" => [0.5686534 0.2814105 … -0.80229354 0.14085971],"W1" => [0.0031251688 -0.0046197865 … -0.005307814 0.010830305; 0.013483216 -0.0020634974 … 0.007007745 -0.014958549; … ; -0.010350274 0.002268731 … 0.0016561231 -0.011203028; 0.016753606 -0.010520669 … 0.0068002143 0.011218524],"b2" => [0.039936557],"b1" => [0.006323702; 0.0; … ; -0.00069409446; -0.00011211381]), (relu, sigmoid))

In [65]:
predicts, accuracy = predict(train_data_x, train_data_y_orig, parameters, activations)

Accuracy is 96.17224880382776%


([0.0 0.0 … 0.0 0.0], 0.9617224880382775)

In [21]:
predicts, accuracy = predict(test_data_x, test_data_y_orig, parameters, activations)

Accuracy is 72.0%


([1.0 1.0 … 1.0 0.0], 0.72)

## Benchmarking

In [22]:
@btime neural_network_dense($train_data_x, $train_data_y_orig, $layer_dims, 100, 0.0075)

Cost at iteration 100 is 0.53558016
Cost at iteration 100 is 0.5029567
Cost at iteration 100 is 0.57660806
Cost at iteration 100 is 0.5272773
Cost at iteration 100 is 0.55313444
Cost at iteration 100 is 0.5367662
Cost at iteration 100 is 0.55328417
Cost at iteration 100 is 0.6030852
Cost at iteration 100 is 0.52965045
Cost at iteration 100 is 0.5038902
Cost at iteration 100 is 0.53633785
Cost at iteration 100 is 0.5288921
  1.448 s (30026 allocations: 1.25 GiB)


(Dict{String,Array{Float32,N} where N}("W2" => [0.61104214 -0.1225971 … 0.07468962 0.6459953],"W1" => [-0.010853113 -0.017955592 … 0.0021657879 0.0037813105; -0.0060843085 0.011459536 … -0.014435871 0.0047255307; … ; 0.012235935 0.012439721 … -0.012860407 0.017553123; -0.015616017 -0.02493834 … 0.00083742593 -0.006985716],"b2" => [-0.012878602],"b1" => [-0.00103546; -0.00015716007; … ; -6.338201e-5; -0.0008261606]), (relu, sigmoid))

In [20]:
@btime initialize_parameters($layer_dims, $train_data_y_orig)

  626.100 μs (37 allocations: 1.64 MiB)


Dict{String,Array{Float32,N} where N} with 4 entries:
  "W2" => Float32[0.026359 0.480013 … 0.189839 0.594478]
  "W1" => Float32[-0.00503414 -0.00485214 … 0.00950346 0.0136017; -0.0118903 -0…
  "b2" => Float32[0.0]
  "b1" => Float32[0.0; 0.0; … ; 0.0; 0.0]

In [22]:
parameters = initialize_parameters(layer_dims, train_data_y_orig)
activations = (relu, sigmoid)
y, caches = forward_prop(train_data_x, parameters, activations)
print()

In [54]:
@btime forward_prop($train_data_x, $parameters, $activations)

  888.801 μs (93 allocations: 24.78 KiB)


(Float32[0.50752395 0.44827378 … 0.49574357 0.46908775], Dict{String,Array{Float32,N} where N}("A2" => [0.50752395 0.44827378 … 0.49574357 0.46908775],"A1" => [0.0 0.0 … 0.0 0.0; 0.2682694 0.6815136 … 0.0348052 0.2630909; … ; 0.0 0.0 … 0.0 0.07128604; 0.21147422 0.49728242 … 0.0 0.19836868],"A0" => [0.06666667 0.76862746 … 0.08627451 0.03137255; 0.12156863 0.7529412 … 0.09411765 0.10980392; … ; 0.0 0.3137255 … 0.019607844 0.0; 0.0 0.31764707 … 0.0 0.0],"Z2" => [0.030098056 -0.20764787 … -0.0170261 -0.12380698],"Z1" => [-0.49418628 -0.71965206 … -0.14185269 -0.4087648; 0.2682694 0.6815136 … 0.0348052 0.2630909; … ; -0.09253468 -0.033902768 … -0.12035904 0.07128604; 0.21147422 0.49728242 … -0.05054159 0.19836868]))

In [24]:
y_orig = Array{Float32, 2}(train_data_y_orig)
cost = cost_binary(y_orig, y)

0.70402896f0

In [56]:
@btime cost_binary($y_orig, $y)

  4.328 μs (1 allocation: 1008 bytes)


0.67906153f0

In [25]:
activations_back = (relu_back, sigmoid_back)
grads = backward_prop(y_orig, y, parameters, caches, layer_dims, activations_back)

Dict{String,Array{Float32,N} where N} with 4 entries:
  "dw1" => Float32[-0.000152993 -0.000131177 … -9.79547e-5 -7.17154e-5; 0.00371…
  "dw2" => Float32[0.000100806 0.00691432 … 0.00506449 0.0219995]
  "db2" => Float32[0.176907]
  "db1" => Float32[-0.000346978; 0.0116318; … ; -0.00401343; 0.0728398]

In [58]:
@btime backward_prop($y_orig, $y, $parameters, $caches, $layer_dims, $activations_back) 

  4.291 ms (118 allocations: 11.13 MiB)


Dict{String,Array{Float32,N} where N} with 4 entries:
  "dw1" => Float32[9.16046e-5 0.000189444 … 0.000311732 0.000235581; -0.0048612…
  "dw2" => Float32[0.00429011 0.0378653 … 0.00325473 0.0385711]
  "db2" => Float32[0.122613]
  "db1" => Float32[0.000443472; -0.0184071; … ; -0.017111; -0.0128261]

In [26]:
learning_rate = 0.000001
parameters = update_parameters(parameters, grads, layer_dims, learning_rate)

Dict{String,Array{Float32,N} where N} with 4 entries:
  "W2" => Float32[-0.0340573 0.210562 … -0.105929 0.575805]
  "W1" => Float32[0.000618291 -0.00256079 … 0.00925934 -0.00127785; 0.00316973 …
  "b2" => Float32[-1.76907e-7]
  "b1" => Float32[3.46978e-10; -1.16318e-8; … ; 4.01343e-9; -7.28398e-8]

In [60]:
@btime update_parameters($parameters, $grads, $layer_dims, $learning_rate)

  211.701 μs (87 allocations: 1.64 MiB)


Dict{String,Array{Float32,N} where N} with 4 entries:
  "W2" => Float32[0.0151536 -0.15992 … -0.440818 -0.142001]
  "W1" => Float32[0.0127349 -0.0128757 … -0.0117947 -0.00683415; -0.00448318 0.…
  "b2" => Float32[-0.00245401]
  "b1" => Float32[-8.87552e-6; 0.000368321; … ; 0.000342491; 0.000256664]

In [46]:
@btime neural_network_dense($train_data_x, $train_data_y_orig, $layer_dims, 1, 0.0075)

  5.981 ms (350 allocations: 14.45 MiB)


(Dict{String,Array{Float32,N} where N}("W2" => [0.3276358 -0.2913516 … -0.056624386 1.2782983],"W1" => [0.011470085 0.011604643 … -0.0018633803 0.01096336; -0.0007123757 0.009185629 … 0.00059031637 -0.0012510043; … ; 0.0071292855 -0.017844321 … 0.015887309 -0.00911494; -0.016298955 -0.0042280867 … -0.014126171 0.0070554153],"b2" => [-0.0008734076],"b1" => [-0.00019166565; 0.00018358006; … ; 4.1828876e-5; -2.2047214e-5]), (relu, sigmoid))