In [2]:
using HDF5

┌ Info: Precompiling HDF5 [f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f]
└ @ Base loading.jl:1273


In [3]:
TRAIN_DATA_PATH="datasets/train_catvnoncat.h5"
TEST_DATA_PATH="datasets/test_catvnoncat.h5"

"datasets/test_catvnoncat.h5"

In [6]:
train_data_x_orig = h5read(TRAIN_DATA_PATH, "train_set_x")
train_data_y_orig = h5read(TRAIN_DATA_PATH, "train_set_y")

209-element Array{Int64,1}:
 0
 0
 1
 0
 0
 0
 0
 1
 0
 0
 0
 1
 0
 ⋮
 1
 0
 0
 1
 0
 0
 0
 0
 0
 0
 0
 0

In [7]:
test_data_x_orig = h5read(TEST_DATA_PATH, "test_set_x")
test_data_y_orig = h5read(TEST_DATA_PATH, "test_set_y")

50-element Array{Int64,1}:
 1
 1
 1
 1
 1
 0
 1
 1
 1
 1
 1
 1
 1
 ⋮
 0
 0
 1
 1
 1
 0
 0
 0
 1
 1
 1
 0

In [8]:
classes = h5read(TEST_DATA_PATH, "list_classes")

2-element Array{String,1}:
 "non-cat"
 "cat"    

In [9]:
train_data_y_orig = reshape(train_data_y_orig, (1, size(train_data_y_orig)[1]))

1×209 Array{Int64,2}:
 0  0  1  0  0  0  0  1  0  0  0  1  0  …  1  0  0  1  0  0  0  0  0  0  0  0

In [10]:
test_data_y_orig = reshape(test_data_y_orig, (1, size(test_data_y_orig)[1]))

1×50 Array{Int64,2}:
 1  1  1  1  1  0  1  1  1  1  1  1  1  …  0  0  1  1  1  0  0  0  1  1  1  0

In [21]:
function reshape_image_array(image_array::Array{UInt8,4})
    return reshape(image_array, :, size(image_array)[4])
end
function reshape_image_array_reverse(image_array::Array{UInt8,2})
    return reshape(image_array, 64, 64, 3, :)
end

reshape_image_array_reverse (generic function with 3 methods)

In [136]:
test_data_x = reshape_image_array(test_data_x_orig) ./ 255
test_data_x = Array{Float32, 2}(test_data_x)

12288×50 Array{Float32,2}:
 0.619608  0.45098   1.0       0.996078  …  0.160784  0.0705882  0.521569 
 0.407843  0.431373  0.992157  0.996078     0.184314  0.0705882  0.639216 
 0.32549   0.435294  0.996078  0.952941     0.329412  0.0627451  0.294118 
 0.631373  0.537255  1.0       1.0          0.282353  0.137255   0.384314 
 0.415686  0.505882  0.992157  1.0          0.305882  0.141176   0.470588 
 0.333333  0.505882  0.996078  0.964706  …  0.439216  0.121569   0.172549 
 0.635294  0.607843  1.0       1.0          0.403922  0.211765   0.423529 
 0.419608  0.572549  0.992157  1.0          0.4       0.223529   0.517647 
 0.329412  0.568627  0.996078  0.992157     0.486275  0.203922   0.184314 
 0.639216  0.623529  1.0       1.0          0.466667  0.313726   0.462745 
 0.419608  0.596078  0.992157  1.0       …  0.447059  0.345098   0.576471 
 0.329412  0.572549  0.996078  1.0          0.505882  0.313726   0.223529 
 0.639216  0.607843  1.0       1.0          0.529412  0.407843   0.403922

In [137]:
train_data_x = reshape_image_array(train_data_x_orig) ./ 255
train_data_x = Array{Float32, 2}(train_data_x)

12288×209 Array{Float32,2}:
 0.0666667  0.768627  0.321569  0.00392157  …  0.560784  0.0862745  0.0313726
 0.121569   0.752941  0.278431  0.0862745      0.607843  0.0941176  0.109804 
 0.219608   0.745098  0.266667  0.00784314     0.647059  0.0901961  0.207843 
 0.0862745  0.756863  0.34902   0.00392157     0.721569  0.0901961  0.054902 
 0.129412   0.729412  0.32549   0.054902       0.745098  0.0980392  0.129412 
 0.231373   0.713726  0.32549   0.00784314  …  0.776471  0.0941176  0.227451 
 0.0980392  0.737255  0.392157  0.00392157     0.556863  0.0941176  0.0745098
 0.137255   0.701961  0.384314  0.0509804      0.584314  0.101961   0.137255 
 0.243137   0.682353  0.407843  0.00392157     0.607843  0.0980392  0.239216 
 0.0980392  0.835294  0.415686  0.0156863      0.529412  0.0941176  0.0745098
 0.137255   0.760784  0.411765  0.113725    …  0.580392  0.101961   0.137255 
 0.243137   0.756863  0.454902  0.0117647      0.596078  0.105882   0.239216 
 0.105882   0.658824  0.462745  0.03

In [138]:
using Statistics

In [167]:
include("../../NeuralNetwork.jl")

predict (generic function with 1 method)

In [173]:
parameters, activations = neural_network_dense(train_data_x, train_data_y_orig, [12288, 7, 1], 1000, 0.0075)

(relu, sigmoid)
(relu_back, sigmoid_back)
	Initial Mean of parameter W2 is 0.09781615
	Initial Variance of parameter W2 is 0.16806696
	Initial Mean of parameter W1 is 1.8055047e-5
	Initial Variance of parameter W1 is 8.116708e-5
	Initial Mean of parameter b2 is 0.0
	Initial Variance of parameter b2 is NaN
	Initial Mean of parameter b1 is 0.0
	Initial Variance of parameter b1 is 0.0
Cost at iteration 100 is 0.58959836
	Mean of parameter W2 is 0.085055895
	Variance of parameter W2 is 0.17748964
	Mean of parameter W1 is -2.7825146e-5
	Variance of parameter W1 is 8.168661e-5
	Mean of parameter b2 is -0.013863018
	Variance of parameter b2 is NaN
	Mean of parameter b1 is 0.00079932617
	Variance of parameter b1 is 3.7481857e-6
Cost at iteration 200 is 0.5312885
	Mean of parameter W2 is 0.065058164
	Variance of parameter W2 is 0.196458
	Mean of parameter W1 is -4.605148e-5
	Variance of parameter W1 is 8.276643e-5
	Mean of parameter b2 is -0.011200184
	Variance of parameter b2 is NaN
	Mean of p

(Dict{String,Array{Float32,N} where N}("W2" => [-0.42544857 0.9675515 … -0.6099776 0.3687511],"W1" => [-0.010610555 0.008144683 … 0.0059850262 0.019291883; -0.0040354966 0.0013157723 … 0.0102731595 0.002488309; … ; -0.019092584 0.02234779 … 0.010451086 -0.0077486434; 0.008650074 0.02369215 … -0.005745986 0.006797685],"b2" => [0.015745487],"b1" => [0.00459581; -0.0013595674; … ; 0.0082442295; 0.0036061301]), (relu, sigmoid))

In [175]:
predicts, accuracy = predict(train_data_x, train_data_y_orig, parameters, activations)

Accuracy is 96.65071770334929%


([0.0 0.0 … 0.0 0.0], 0.9665071770334929)

In [176]:
predicts, accuracy = predict(test_data_x, test_data_y_orig, parameters, activations)

Accuracy is 76.0%


([1.0 1.0 … 1.0 0.0], 0.76)