In [75]:
# inputs for XOR
# each column contains the vector of input (A and B)
# 4 columns = 4 inputs
X = [0 0 1 1; 0 1 0 1]
X = Array{Float32, 2}(X)

2×4 Array{Float32,2}:
 0.0  0.0  1.0  1.0
 0.0  1.0  0.0  1.0

In [76]:
# shape of X should be (num_features, num_examples)
size(X)

(2, 4)

In [77]:
# corresponding outputs (to each columns)
Y = [0, 1, 1, 0]

4-element Array{Int64,1}:
 0
 1
 1
 0

In [78]:
num_features = 2  # size of each input vector
num_hidden_layer_neurons = 5  # Number of neurons in hidden layer
layer_dims = [num_features, num_hidden_layer_neurons, 1]

3-element Array{Int64,1}:
 2
 5
 1

In [64]:
include("../../NeuralNetwork.jl")

predict

In [81]:
# train the NN to get trained parameters (and activations, which is used for predicting)
params, acts = neural_network_dense(X, Y, layer_dims, 10000, 0.01)
print()

Cost at iteration 100 is 0.6736331
Cost at iteration 200 is 0.6651842
Cost at iteration 300 is 0.65598464
Cost at iteration 400 is 0.6455958
Cost at iteration 500 is 0.6337347
Cost at iteration 600 is 0.6202123
Cost at iteration 700 is 0.6048673
Cost at iteration 800 is 0.588391
Cost at iteration 900 is 0.5728771
Cost at iteration 1000 is 0.55614275
Cost at iteration 1100 is 0.53806245
Cost at iteration 1200 is 0.51899457
Cost at iteration 1300 is 0.49866766
Cost at iteration 1400 is 0.47745
Cost at iteration 1500 is 0.4554162
Cost at iteration 1600 is 0.43302107
Cost at iteration 1700 is 0.410481
Cost at iteration 1800 is 0.3877384
Cost at iteration 1900 is 0.3654736
Cost at iteration 2000 is 0.34360135
Cost at iteration 2100 is 0.32258868
Cost at iteration 2200 is 0.30259347
Cost at iteration 2300 is 0.2834548
Cost at iteration 2400 is 0.26554203
Cost at iteration 2500 is 0.24873295
Cost at iteration 2600 is 0.23317467
Cost at iteration 2700 is 0.21879037
Cost at iteration 2800 is 0.

In [83]:
# predict and find accuracy
predicts, acc = predict(X, Y, params, acts)

Accuracy is 100.0%


([0.0 1.0 1.0 0.0], 1.0)

In [84]:
# give example inputs here
A = 0
B = 1

input = reshape(Array{Float32}([A; B]), 2, :)
predicts, acc = predict(input, nothing, params, acts)
result = Int(predicts[1])
println("XOR of $A and $B is $result")

XOR of 0 and 1 is 1
